### ISSUE TITLE
Refatoração geral do projeto

### ISSUE THREAD

**Issue by miguelarauj1o** [rafaelfccg/spaceAttack#5]

**Comment by rafaelfccg** [comment]
Itens Para serem refatorados:
Criar uma classe que herda de SKSpriteNode para cada tipo de nó utilizado.
Em cada subclasse de skspritenode deve conter todo controle e lógica associada a esse no. Ela também deve cuidar do armazenamento em memória dos assets para as animações, audios, e particle emmitter relativos a esse nó, ou seja, um asteroid deve conter nele(talvez estaticamente já que é a mesma animaçao para todos asteroid), uma SKAction que cuida da animaçao do asteroid. 

Criar protocolos para os inimigos. Por exemplo toda nave inimiga deve implementar um protocol que contenha  a ação de atirar e cada um define como vai ser seu tiro. Ao mesmo tempo qualquer objeto que possa ser atingido por um tiro deve implementar um protocolo que contenha o método "receber dano". 

Separar de alguma forma a lógica do tiro da nave do nó criado para nave. (Usar composição). Desse jeito fica mais fácil produzir itens novos caso necessário. Essa logica também pode ser parametrizada.(parametros: frequencia do tiro, tamanho do tiro, etc)

Separar a parte de física numa extension. 
Criar um singleton para controle da musica de Background

**Comment by miguelarauj1o** [comment]
Massa. Farei tudo!

**Comment by miguelarauj1o** [comment]
merged in #17
